### ISSUE TITLE
Requesting attachement of Documents

### ISSUE THREAD

**Issue by RevathiRavi0626** [RevathiRaviTesting1996/WhatsUp_Development#7]
Hi Revathi,

it would be great if the app is capable of attaching the document as well. kindly add this feature.

**Comment by RevathiRaviTesting1996** [comment]
Hi Ravi,

thanks for suggesting this feature. we will add and let you know.

**Comment by RevathiRaviTesting1996** [comment]
Hi Ravi,

Thanks for your valuable suggestions. This feature is going to make our product great.
